- Topics Studied:
    - How to Improve Training Pipeline:
        - NN Module 
        - torch.optim module
    - What are the improvements:
        - not give parameters manually
        - used built in loss function
        - used built in activation function
        - not update parameter manually will use torch.optim
    - Summary:
        - Built an nueral network using nn module
        - Use built in activation function
        - Use built in loss function
        - Use built in optimizer

- The nn module:
    - nn module is an liabrary of pytorch that provide wide range of classes and functions designed to help developer to build neural network efficiently and effectively.
    - It abstracts the complexity of creating and training neural network by offering pre-built layers, loss functions, activation functions and other utilities.

- Key Components of torch.nn:
1) Modules(Layers):
    - nn.Module : The base class for all nueral network modules. Your custom models and layers should subclass this class.
    - Common Layers : Include layers like nn.Linear (fully connected layer), nn.Conv2D (convolutional layer), nn.LSTM (reccurent layer) and many others.

2) Activation Functions:
    - Functions like nn.ReLU, nn.Sigmoid and nn.Tanh itroduce non-linearities to the model, allowing it to learn complex patterns.

3) Loss Functions:
    - Provide loss functions such as nn.CrossEntropyLoss, nn,MSELoss and nn.NLLLoss to quanify the differnce between the model's predictions and the actual targets/

4) Container Modules:
    - nn.Sequential : A sequential container to stack layers in orders.

5) Regularization and Dropout:
    - Layer like nn.Dropout and nn.BatchNorm1d help prevent overfitting and improves the model's ability to generalize new data.

In [6]:
# create model class
import torch
import torch.nn as nn

class Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.linear = nn.Linear(num_features,1)
        self.sigmoid = nn.Sigmoid()

    def forward(self,features):
        out = self.linear(features)
        out = self.sigmoid(out)
        return out

In [7]:
# create dataset
features = torch.rand(10,5)

#create model
model = Model(features.shape[1])

# call model and forward pass
model(features)

tensor([[0.4489],
        [0.4987],
        [0.5046],
        [0.4673],
        [0.5005],
        [0.5077],
        [0.4622],
        [0.4915],
        [0.4294],
        [0.4860]], grad_fn=<SigmoidBackward0>)

In [8]:
# show model weights
model.linear.weight

Parameter containing:
tensor([[ 0.2088, -0.0418, -0.1466, -0.3368, -0.1829]], requires_grad=True)

In [9]:
# show model bias
model.linear.bias

Parameter containing:
tensor([0.2119], requires_grad=True)

In [10]:
%pip install torchinfo

Collecting torchinfo
  Downloading torchinfo-1.8.0-py3-none-any.whl.metadata (21 kB)
Downloading torchinfo-1.8.0-py3-none-any.whl (23 kB)
Installing collected packages: torchinfo
Successfully installed torchinfo-1.8.0

In [11]:
from torchinfo import summary
summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
==========================================================================================
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [22]:
# create new nn
# input layer 5 nuerons 
# hidden layer 3 nuerons
# output layer 1 nueron (y_pred)

import torch
import torch.nn as nn

class New_Model(nn.Module):
    def __init__(self,num_features):
        super().__init__()
        self.network = nn.Sequential(
            nn.Linear(num_features,3),
            nn.ReLU(),
            nn.Linear(3,1),
            nn.Sigmoid()
        )

    def forward(self,features):
        out = self.network(features)
        return out

In [23]:
# create dataset
features = torch.rand(10,5)

#create model
model = New_Model(features.shape[1])

# call model and forward pass
model(features)

tensor([[0.5356],
        [0.5356],
        [0.5356],
        [0.5356],
        [0.5356],
        [0.5356],
        [0.5356],
        [0.5356],
        [0.5356],
        [0.5356]], grad_fn=<SigmoidBackward0>)

In [25]:
from torchinfo import summary
summary(model,input_size=(10,5))

==========================================================================================
Layer (type:depth-idx)                   Output Shape              Param #
==========================================================================================
New_Model                                [10, 1]                   --
├─Sequential: 1-1                        [10, 1]                   --
│    └─Linear: 2-1                       [10, 3]                   18
│    └─ReLU: 2-2                         [10, 3]                   --
│    └─Linear: 2-3                       [10, 1]                   4
│    └─Sigmoid: 2-4                      [10, 1]                   --
==========================================================================================
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
==========================================================================================
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00
==========================================================================================

In [28]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [29]:
df = pd.read_csv("breast_cancer_data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [30]:
df.shape

(569, 33)

In [31]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [32]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [33]:
x = df.drop(columns="diagnosis")
y = df["diagnosis"]
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

scaling

In [34]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

label encoding

In [35]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

array to tensor

In [36]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

defining model

In [ ]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
        
    def forward(self,X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred,y):
        # clamp prediction to avoide log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor)* torch.log(1-y_pred)).mean()
        return loss

important parameters

In [ ]:
learning_rate = 0.1
epochs = 35

training pipeline

In [ ]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")