PyTorch Training Pipeline

- Take a DataSet :
    - Build a small neural network on it
    - Understand Training Piepline in PyTorch through this
    - It can be used for all nueral network
    - In this have manual elements
    - End Goal is understand how to build nueral network in PyTorch

- Control Flow :
    - Load Data
    - Basic Preprocessing
    - Training Process
        - Create the model (single nueron (30 input feature so 30 weights and 1 bias))
        - Forward Pass
        - Loss Function
        - Backpropogation (Backward Pass)
        - Parameter Update
    - Model evaluation (accuracy is used)

In [192]:
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [193]:
df = pd.read_csv("breast_cancer_data.csv")
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN

In [194]:
df.shape

(569, 33)

In [195]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [196]:
df.head()

,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,symmetry_mean,...,radius_worst,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst
0,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,0.2419,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,0.1812,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,0.2069,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,0.2597,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,0.1809,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678

train test split

In [197]:
x = df.drop(columns="diagnosis")
y = df["diagnosis"]
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

scaling

In [198]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [199]:
X_train

array([[ 0.37720202,  1.09244233,  0.48583765, ...,  1.51911037,
         0.12671296,  1.2307748 ],
       [ 1.33073061,  0.63007062,  1.30588579, ...,  0.83265305,
         0.11723786, -0.06263883],
       [-0.24145642, -1.29647815, -0.25632652, ..., -0.36027399,
        -0.31072077, -0.60833201],
       ...,
       [-0.07118345, -0.72668675, -0.15000872, ..., -1.0597061 ,
        -0.6170823 , -0.99097603],
       [ 0.20976694, -0.60759101,  0.27320206, ...,  1.31392752,
         1.03000571,  1.21979506],
       [-0.33226867, -0.22928689, -0.32267212, ..., -0.74725487,
         0.43307449, -0.64840807]])

Label encoding

In [200]:
encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [201]:
y_train

array([1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1,
       1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1,
       0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1,
       1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1,
       0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0])

NumPy arrays to PyTorch Tensors

In [202]:
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

In [203]:
X_train_tensor.shape

torch.Size([455, 30])

In [204]:
y_train_tensor.shape

torch.Size([455])

Defining Model

In [205]:
class MySimpleNN():
    def __init__(self,X):
        self.weights = torch.rand(X.shape[1],1,dtype=torch.float64,requires_grad=True)
        self.bias = torch.zeros(1,dtype=torch.float64,requires_grad=True)
        
    def forward(self,X):
        z = torch.matmul(X, self.weights) + self.bias
        y_pred = torch.sigmoid(z)
        return y_pred
    
    def loss_function(self, y_pred,y):
        # clamp prediction to avoide log(0)
        epsilon = 1e-7
        y_pred = torch.clamp(y_pred,epsilon,1-epsilon)

        # calculate loss
        loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor)* torch.log(1-y_pred)).mean()
        return loss

Important Parameters

In [206]:
learning_rate = 0.1
epochs = 35

Training Pipline

In [207]:
# create model
model = MySimpleNN(X_train_tensor)

# define loop
for epoch in range(epochs):
    # forward pass
    y_pred = model.forward(X_train_tensor)
    
    # loss calculate
    loss = model.loss_function(y_pred, y_train_tensor)

    # backward pass
    loss.backward()

    # parameters update
    with torch.no_grad():
        model.weights -= learning_rate * model.weights.grad
        model.bias -= learning_rate * model.bias.grad

    # zero gradients
    model.weights.grad.zero_()
    model.bias.grad.zero_()

    # print loss in each epoch
    print(f"Epoch: {epoch + 1}, Loss: {loss.item()}")

Epoch: 1, Loss: 3.5801791240196135
Epoch: 2, Loss: 3.453095141601755
Epoch: 3, Loss: 3.3216106591230177
Epoch: 4, Loss: 3.18857643709411
Epoch: 5, Loss: 3.0522609135460885
Epoch: 6, Loss: 2.912107977622634
Epoch: 7, Loss: 2.768851170074306
Epoch: 8, Loss: 2.6258605758103375
Epoch: 9, Loss: 2.482922015865681
Epoch: 10, Loss: 2.3427919620489273
Epoch: 11, Loss: 2.201664253238667
Epoch: 12, Loss: 2.0574137894143014
Epoch: 13, Loss: 1.9169917261894713
Epoch: 14, Loss: 1.7828620728779705
Epoch: 15, Loss: 1.6530400441321316
Epoch: 16, Loss: 1.5319677716804065
Epoch: 17, Loss: 1.4199823597095151
Epoch: 18, Loss: 1.319649300901722
Epoch: 19, Loss: 1.2286264880812447
Epoch: 20, Loss: 1.149543536183673
Epoch: 21, Loss: 1.0817233881355175
Epoch: 22, Loss: 1.0241948858621555
Epoch: 23, Loss: 0.9758028937514799
Epoch: 24, Loss: 0.9353192469396123
Epoch: 25, Loss: 0.901537509412799
Epoch: 26, Loss: 0.8733416043772635
Epoch: 27, Loss: 0.8497496879011044
Epoch: 28, Loss: 0.8299351258680056
Epoch: 29, Loss: 0.8132250957126018
Epoch: 30, Loss: 0.7990818498255002
Epoch: 31, Loss: 0.7870760513540618
Epoch: 32, Loss: 0.7768607436638079
Epoch: 33, Loss: 0.7681504828927956
Epoch: 34, Loss: 0.7607064979521829
Epoch: 35, Loss: 0.7543268075683333

In [208]:
model.weights

tensor([[-0.1227],
        [-0.0978],
        [-0.2587],
        [-0.1624],
        [-0.1162],
        [ 0.2617],
        [ 0.3175],
        [-0.3368],
        [ 0.0197],
        [ 0.1532],
        [ 0.0589],
        [-0.2064],
        [-0.0210],
        [ 0.5133],
        [ 0.2273],
        [-0.3192],
        [ 0.3295],
        [-0.4124],
        [ 0.2610],
        [ 0.1652],
        [-0.0764],
        [ 0.3964],
        [ 0.0457],
        [ 0.4565],
        [ 0.1704],
        [-0.2745],
        [ 0.0188],
        [-0.3047],
        [-0.1043],
        [ 0.1560]], dtype=torch.float64, requires_grad=True)

In [209]:
model.bias

tensor([-0.1704], dtype=torch.float64, requires_grad=True)

Evaluation

In [210]:
# model evaluation
with torch.no_grad():
    y_pred = model.forward(X_test_tensor)
    y_pred = (y_pred > 0.5).float()
    accuracy = (y_pred == y_test_tensor).float().mean()
print(f"Accuracy: {accuracy.item()}")

Accuracy: 0.5678670406341553